export default {
  EC_Bold_Italic: 'Euclid Circular B Bold Italic',
  EC_Bold: 'Euclid Circular B Bold',
  EC_Italic: 'Euclid Circular B Italic',
  EC_Light: 'Euclid Circular B Light',
  EC_Light_Italic: 'Euclid Circular B Light Italic',
  EC_Medium: 'Euclid Circular B Medium',
  EC_Medium_Italic: 'Euclid Circular B Medium Italic',
  EC: 'Euclid Circular B Regular',
  EC_Semibold: 'Euclid Circular B Semibold',
  EC_Semibold_Italic: 'Euclid Circular B Semibold Italic',
  Ara_Thin: 'Araboto Thin',
  Ara_Bold: 'Araboto Bold',
  Ara_Black: 'Araboto Black',
  Ara_Medium: 'Araboto Medium',
  Ara: 'Araboto Normal',
};
